FROM python:3.11.7

WORKDIR /code

# OS requirements
RUN DEBIAN_FRONTEND=noninteractive && echo "Installing ODBC Driver" && \
    curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc && \
    curl https://packages.microsoft.com/config/debian/11/prod.list | tee /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y --no-install-recommends msodbcsql17 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    unset DEBIAN_FRONTEND

# Copy only the requirements files first
COPY requirements.txt test_requirements.txt /code/

# Install Python requirements
RUN echo "Installing Python requirements" && \
    pip install --upgrade pip && \
    pip install --no-cache-dir --upgrade -r /code/requirements.txt && \
    pip install --no-cache-dir --upgrade -r /code/test_requirements.txt


# Copy the entire project directory into the container
COPY app /code/app
COPY .coveragerc /code/.coveragerc
COPY conftest.py /code/conftest.py
COPY pytest.ini /code/pytest.ini
COPY tenacity.yaml /code/tenacity.yaml

# Run pytest
RUN echo "Running pytest" && pytest --cov=.

RUN useradd -m nonroot
USER nonroot
