// <auto-generated />
using System;
using EY.CE.Copilot.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EY.CE.Copilot.Data.Migrations
{
    [DbContext(typeof(CopilotContext))]
    [Migration("20240515130948_RemovingTagWIthXYZInSuggestion")]
    partial class RemovingTagWIthXYZInSuggestion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.ChatHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SuggestionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TimeToResolve")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ChatHistorys");
                });

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.CopilotConfiguration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CopilotConfigurations", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsEnabled = false,
                            Key = "PROJECT_CONTEXT",
                            Title = "Project Context",
                            Value = ""
                        });
                });

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.CopilotFeedback", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("CopilotFeedbacks");
                });

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.MessageFeedback", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("bit");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("MessageFeedbacks");
                });

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.Suggestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnswerSQL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppAffinity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Suggestions", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AnswerSQL = "SELECT pt.Title, COUNT(wp.WorkPlanTaskType) AS MilestoneCount FROM WorkPlan wp LEFT JOIN ProjectTeams pt ON pt.ID = wp.ProjectTeamId WHERE wp.WorkPlanTaskType = 'Milestone' GROUP BY pt.Title",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many milestones does each team have?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 2,
                            AnswerSQL = "SELECT pt.Title, COUNT(*) AS RiskCount FROM RisksAndIssues RI left join ProjectTeams pt on pt.ID = ri.ProjectTeamId WHERE IssueRiskCategory = 'Risk' GROUP BY pt.Title",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many risks does each team have?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 3,
                            AnswerSQL = "SELECT      ReceiverTeam.Title AS ReceiverTeamName,     COUNT(1) AS InterdependencyCount FROM      Interdependencies AS I INNER JOIN      ProjectTeams AS ReceiverTeam ON I.ReceiverProjectTeamId = ReceiverTeam.ID GROUP BY      ReceiverTeam.Title",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many interdependencies does each receiver team have?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 4,
                            AnswerSQL = "SELECT wp.Title  from WorkPlan wp  LEFT JOIN Statuses s on wp.WorkPlanTaskStatusId = s.ID  where s.[Key] = 'BEHIND_SCHEDULE'  AND wp.WorkPlanTaskType = 'Milestone'",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out behind schedule milestones",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 5,
                            AnswerSQL = "SELECT RI.Title  from RisksAndIssues RI  LEFT JOIN Statuses s on RI.ItemStatusId = s.ID  where s.[Key] = 'BEHIND_SCHEDULE'  AND RI.IssueRiskCategory = 'Risk'",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out behind schedule risks",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 6,
                            AnswerSQL = "SELECT I.Title  from Interdependencies I  LEFT JOIN InterdependencyStatuses s on I.InterdependencyStatusId = s.ID  where s.[Key] = 'BEHIND_SCHEDULE'",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out behind schedule interdependencies",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 7,
                            AnswerSQL = "SELECT COUNT(*) AS MilestonesDueThisWeek FROM WorkPlan wp LEFT JOIN statuses s ON wp.WorkPlanTaskStatusId = s.ID LEFT JOIN UserProfiles up on wp.TaskOwnerId = up.ID WHERE wp.WorkPlanTaskType = 'Milestone'   AND YEAR(wp.TaskDueDate) = YEAR(GETDATE())   AND DATEPART(WEEK, wp.TaskDueDate) = DATEPART(WEEK, GETDATE())   AND (s.[Key] IS NULL OR s.[Key]  NOT IN ('COMPLETED', 'CLOSED'))   AND up.EMail = '${Username}'",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many of my milestones are due this week?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 8,
                            AnswerSQL = "SELECT COUNT(*) AS RisksAndIssuesDueThisWeek FROM RisksAndIssues RI LEFT JOIN statuses S ON RI.ItemStatusId = S.ID LEFT JOIN UserProfiles up on RI.ItemOwnerId = up.ID WHERE RI.IssueRiskCategory = 'Risk'   AND YEAR(RI.ItemDueDate) = YEAR(GETDATE())   AND DATEPART(WEEK, RI.ItemDueDate) = DATEPART(WEEK, GETDATE())   AND (S.[Key] IS NULL OR S.[Key] NOT IN ('COMPLETED', 'CLOSED'))   AND up.EMail = '${Username}'",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many of my risks are due this week?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 9,
                            AnswerSQL = "SELECT      COUNT(*) AS InterdependenciesDueThisWeek FROM      Interdependencies I LEFT JOIN      statuses S ON I.InterdependencyStatusId = S.ID WHERE      YEAR(I.ItemDueDate) = YEAR(GETDATE())     AND DATEPART(WEEK, I.ItemDueDate) = DATEPART(WEEK, GETDATE())     AND (S.[Key] IS NULL OR S.[Key] NOT IN ('COMPLETED', 'CLOSED'))",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many interdependencies are due this week",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 10,
                            AnswerSQL = "SELECT     pt.Title AS ProjectTeamTitle,     COUNT(*) AS OverdueMilestoneCount FROM      WorkPlan wp INNER JOIN      ProjectTeams pt ON wp.ProjectTeamId = pt.ID LEFT JOIN      statuses s ON wp.WorkPlanTaskStatusId = s.ID WHERE      wp.WorkPlanTaskType = 'Milestone'     AND wp.TaskDueDate < GETDATE()     AND (s.[Key] IS NULL OR s.[Key] NOT IN ('COMPLETED', 'CLOSED')) GROUP BY      pt.Title ORDER BY      OverdueMilestoneCount DESC",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which project team has the most overdue milestones",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 11,
                            AnswerSQL = "SELECT      pt.Title AS ProjectTeamTitle,     COUNT(1) AS OverdueRiskCount FROM      RisksAndIssues RI INNER JOIN      ProjectTeams pt ON RI.ProjectTeamId = pt.ID LEFT JOIN      statuses S ON RI.ItemStatusId = S.ID WHERE      RI.IssueRiskCategory = 'Risk'     AND RI.ItemDueDate < GETDATE()     AND (S.[Key] IS NULL OR S.[Key] NOT IN ('COMPLETED', 'CLOSED')) GROUP BY      pt.Title ORDER BY  OverdueRiskCount desc",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which project team has the most overdue risks?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 12,
                            AnswerSQL = "SELECT      ProviderTeam.Title AS ProviderTeamTitle,     COUNT(1) AS OverdueDependencyCount FROM      Interdependencies I INNER JOIN      ProjectTeams ProviderTeam ON I.ProviderProjectTeamId = ProviderTeam.ID LEFT JOIN      InterdependencyStatuses S ON I.InterdependencyStatusId = S.ID WHERE      I.ItemDueDate < GETDATE()     AND (S.[Key] IS NULL OR S.[Key] NOT IN ('COMPLETED', 'CLOSED')) GROUP BY      ProviderTeam.Title ORDER BY      OverdueDependencyCount DESC",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which provider project team has the most overdue interdependencies?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 13,
                            AnswerSQL = "SELECT      RiskImpact,     RiskProbability,     COUNT(*) AS RiskCount FROM      RisksAndIssues WHERE      IssueRiskCategory = 'Risk'     AND ItemStatusId NOT IN (SELECT ID FROM statuses WHERE [Key] IN ('COMPLETED', 'CLOSED'))  AND (RiskImpact IS NOT NULL   OR RiskProbability IS NOT NULL  ) GROUP BY      RiskImpact,     RiskProbability ORDER BY      RiskImpact, RiskProbability",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me open risks broken down by impact and probability",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 14,
                            AnswerSQL = "SELECT      ReceiverTeam.Title AS ReceiverTeamTitle,     COUNT(1) AS OverdueDependencyCount FROM      Interdependencies I INNER JOIN      ProjectTeams ReceiverTeam ON I.ReceiverProjectTeamId = ReceiverTeam.ID LEFT JOIN      InterdependencyStatuses S ON I.InterdependencyStatusId = S.ID WHERE      I.ItemDueDate < GETDATE()     AND (S.[Key] IS NULL OR S.[Key] NOT IN ('COMPLETED', 'CLOSED')) GROUP BY      ReceiverTeam.Title ORDER BY      OverdueDependencyCount DESC",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which receiver project team has the most overdue interdependencies?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 15,
                            AnswerSQL = "SELECT      ProviderTeam.Title AS ProviderTeamame,     COUNT(1) AS InterdependencyCount FROM      Interdependencies AS I INNER JOIN      ProjectTeams AS ProviderTeam ON I.ProviderProjectTeamId = ProviderTeam.ID GROUP BY      ProviderTeam.Title",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many interdependencies does each provider team have ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 16,
                            AnswerSQL = "SELECT 'Total Top Down Target' AS KPI, FORMAT((SUM(HeadcountCostReductionEst)+SUM(NonHeadcountCostReductionEst)+SUM(RevenueGrowthEstimate))/1000000,'N2') AS 'Value (Million)' FROM ValueCaptureTopDownEstimates ",
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are our targets for this engagement?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 17,
                            AnswerSQL = "DECLARE @Y INT; DECLARE @ColumnName NVARCHAR(50); DECLARE @SqlQuery NVARCHAR(MAX);  SELECT @Y = TRY_CAST(JSON_VALUE([Value], '$[0].defaultValue.Id') AS INT) FROM MetastoreGeneralSettings WHERE [Key] = 'VC_PROJECT_TIMEFRAME_CADENCE';  SET @ColumnName = 'Y' + CAST(@Y AS NVARCHAR(10)) + 'M12Estimate';  SET @SqlQuery = '     SELECT (SUM(ISNULL (' + QUOTENAME(@ColumnName) + ', 0))*12)/1000000 AS ValuetoAchieve FROM ValueCaptureEstimates VCE JOIN ValueCaptureInitiatives VCI ON VCE.ValueCaptureInitiativeId = VCI.ID WHERE ISNULL(VCE.Recurring,0) = 1 AND VCI.IsItemActive=1 AND ProjectTeamID IN (SELECT ID FROM ProjectTeams WHERE ManageValueCapture = 1 AND TeamTypeID = 1) AND ValueCaptureValueTypeId = 1';  EXEC sp_executesql @SqlQuery",
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How much value are we planning to achieve from our initiatives?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 18,
                            AnswerSQL = "SELECT S.Title, COUNT(VI.ID) AS InitiativeCount FROM ValueCaptureStages S LEFT JOIN ValueCaptureInitiatives VI ON S.ID = VI.ValueCaptureStageId LEFT JOIN UserProfiles UP on UP.ID = VI.ItemOwnerId Where UP.EMail = '${Username}' GROUP BY S.Title ",
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How are my initiatives doing?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 19,
                            AnswerSQL = "SELECT RI.Title FROM RisksAndIssuesToValueCaptureInitiativesForValueCaptureInitiativeIDs RIV JOIN ValueCaptureInitiatives VI ON VI.ID = RIV.ValueCaptureInitiativeId JOIN RisksAndIssues RI ON RI.ID = RIV.RisksAndIssueId JOIN UserProfiles U ON U.ID = VI.ItemOwnerId WHERE U.Email = '${Username}' ",
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Are there any risks or issues with initiatives that I’m responsible for?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 20,
                            AnswerSQL = "DECLARE @Y INT; DECLARE @ColumnName NVARCHAR(50); DECLARE @SqlQuery NVARCHAR(MAX); DECLARE @TotalEstimate DECIMAL(18,2);  SELECT @Y = TRY_CAST(JSON_VALUE([Value], '$[0].defaultValue.Id') AS INT) FROM MetastoreGeneralSettings WHERE [Key] = 'VC_PROJECT_TIMEFRAME_CADENCE';  SET @ColumnName = 'Y' + CAST(@Y AS NVARCHAR(10)) + 'M12Estimate';  SET @SqlQuery = '     SELECT @TotalEstimate = (SUM(ISNULL (' + QUOTENAME(@ColumnName) + ', 0))*12)     FROM ValueCaptureEstimates VCE      JOIN ValueCaptureInitiatives VCI ON VCE.ValueCaptureInitiativeId = VCI.ID      WHERE ISNULL(VCE.Recurring,0) = 1      AND VCI.IsItemActive=1     AND ProjectTeamID IN (SELECT ID FROM ProjectTeams WHERE ManageValueCapture = 1 AND TeamTypeID = 1)     AND ValueCaptureValueTypeId = 1';  EXEC sp_executesql @SqlQuery, N'@TotalEstimate DECIMAL(18,2) OUTPUT', @TotalEstimate OUTPUT;  WITH SubtractedValue AS (    SELECT 'Total Top Down Target' AS KPI,    FORMAT((@TotalEstimate - (SUM(HeadcountCostReductionEst)+SUM(NonHeadcountCostReductionEst)+SUM(RevenueGrowthEstimate)))/1000000,'N2') AS 'Value (Million)'     FROM ValueCaptureTopDownEstimates ) SELECT * FROM SubtractedValue ",
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Are our initiative projections exceeding our targets?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 21,
                            AnswerSQL = "select VI.Title from ValueCaptureInitiatives VI LEFT JOIN UserProfiles U on U.ID = VI.ItemOwnerId where U.EMail = '${Username}' ",
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How  many initiatives are assigned to me? ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 22,
                            AnswerSQL = "SELECT VI.Title  FROM ValueCaptureInitiatives VI LEFT JOIN ValueCaptureTypes VT ON VT.ID = VI.ValueCaptureTypeId LEFT JOIN UserProfiles U ON U.ID = VI.ItemOwnerId WHERE VT.ID = 1 AND U.EMail = '${Username}' ",
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Give my cost reduction initiatives ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 23,
                            AnswerSQL = "SELECT D.Title, STRING_AGG(N.Title, ', ') AS NodeTitles FROM NodesToDispositionsForDispositionNew ND LEFT JOIN Nodes N ON N.ID = ND.NodeId LEFT JOIN Dispositions D ON D.ID = ND.DispositionId LEFT JOIN TransactionStates T on T.ID = N.TransactionStateId Where T.[Key] = 'DAY_ONE' GROUP BY D.Title ",
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Provide a summary of Day 1 process dispositions.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 24,
                            AnswerSQL = "SELECT DISTINCT S.Title  FROM NodesToSystemsForEnablerSystems NS LEFT JOIN Nodes N ON N.ID = NS.NodesId LEFT JOIN Systems S ON S.ID = NS.SystemsId LEFT JOIN TransactionStates T ON T.ID = N.TransactionStateId WHERE T.[Key] = 'CURRENT_STATE' ",
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many systems are tagged to Current State processes?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 25,
                            AnswerSQL = "SELECT DISTINCT S.Title  FROM NodesToSystemsForEnablerSystems NS LEFT JOIN Nodes N ON N.ID = NS.NodesId LEFT JOIN Systems S ON S.ID = NS.SystemsId LEFT JOIN TransactionStates T ON T.ID = N.TransactionStateId WHERE T.[Key] = 'DAY_ONE' ",
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many systems are tagged to Day 1 processes?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 26,
                            AnswerSQL = "SELECT DISTINCT A.Title  FROM NodesToAssetsForEnablerAssets NA LEFT JOIN Nodes N ON N.ID = NA.NodesId LEFT JOIN Assets A ON A.ID = NA.AssetsId LEFT JOIN TransactionStates T ON T.ID = N.TransactionStateId WHERE T.[Key] = 'DAY_ONE' AND A.Title IS NOT NULL ",
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many assets  are tagged to Day 1 processes? ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 27,
                            AnswerSQL = "SELECT DISTINCT A.Title  FROM NodesToAssetsForEnablerAssets NA LEFT JOIN Nodes N ON N.ID = NA.NodesId LEFT JOIN Assets A ON A.ID = NA.AssetsId LEFT JOIN TransactionStates T ON T.ID = N.TransactionStateId WHERE T.[Key] = 'CURRENT_STATE' AND A.Title IS NOT NULL ",
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many assets are tagged to Current State processes? ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 28,
                            AnswerSQL = "SELECT Nodes.Title, a.TotalCount FROM (     SELECT COUNT(Title) AS TotalCount, BusinessEntityId      FROM Nodes      WHERE NodeTypeId = 3      GROUP BY BusinessEntityId ) a INNER JOIN Nodes ON a.BusinessEntityId = Nodes.ID ",
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Can you provide me number of processes by op model? ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 29,
                            AnswerSQL = "SELECT Nodes.Title, a.TotalCount FROM (     SELECT COUNT(N.Title) AS TotalCount, BusinessEntityId      FROM Nodes N  LEFT JOIN TransactionStates T ON T.ID = N.TransactionStateId     WHERE NodeTypeId = 3 AND T.[Key] = 'CURRENT_STATE'     GROUP BY BusinessEntityId ) a INNER JOIN Nodes ON a.BusinessEntityId = Nodes.ID ",
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many processes we have in current state? ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 30,
                            AnswerSQL = "SELECT Nodes.Title, a.TotalCount FROM (     SELECT COUNT(N.Title) AS TotalCount, BusinessEntityId      FROM Nodes N  LEFT JOIN TransactionStates T ON T.ID = N.TransactionStateId     WHERE NodeTypeId = 3 AND T.[Key] = 'DAY_ONE'     GROUP BY BusinessEntityId ) a INNER JOIN Nodes ON a.BusinessEntityId = Nodes.ID ",
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many processes we have in Day1 state? ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 31,
                            AnswerSQL = "SELECT F.Title, Count(1) as 'Number Of TSAs' from TSAItems T LEFT JOIN Functions F on F.ID = T.FunctionId Group By F.ID, F.Title ",
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the count of TSAs by function.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 32,
                            AnswerSQL = "SELECT SF.Title, Count(1) as 'Number Of TSAs' from TSAItems T LEFT JOIN SubFunctions SF on SF.ID = T.SubFunctionId where T.SubFunctionId IS NOT NULL Group By SF.ID, SF.Title ",
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the count of TSAs by sub function.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 33,
                            AnswerSQL = "SELECT LE.Title, Count(1) as 'Number Of TSAs' from TSAItems T LEFT JOIN LegalEntities LE on LE.ID = T.ProviderLegalEntityId Group By LE.ID, LE.Title ",
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Give me the list of TSAs by Provider ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 34,
                            AnswerSQL = "SELECT LE.Title, Count(1) as 'Number Of TSAs' from TSAItems T LEFT JOIN LegalEntities LE on LE.ID = T.ReceiverLegalEntityId Group By LE.ID, LE.Title ",
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Give me the list of TSAs by Receiver ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 35,
                            AnswerSQL = "SELECT P.Title, T.Title from TSAItems T LEFT JOIN TSAPhases P on P.ID = T.PhaseId Group By P.ID, P.Title ",
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Can you provide me list of TSAs by phases? ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 36,
                            AnswerSQL = "SELECT T.Title, T.Duration as 'Duration in Month' from TSAItems T where T.Duration is not null ",
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the breakdown of TSAs by duration  ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 37,
                            AnswerSQL = "SELECT PT.Title, Count(1) as 'Number Of TSAs' from TSAItems T LEFT JOIN ProjectTeams PT on PT.ID = T.ProjectTeamId Group by PT.ID, PT.Title ",
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many TSAs does each team have? ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 38,
                            AnswerSQL = "SELECT PT.Title as Team, TT.Title as 'Type'  from ProjectTeams PT LEFT JOIN TeamTypes TT on TT.ID = PT.TeamTypeId where TT.[Key] != 'CAPITAL_EDGE_SUPPORT' order by TT.Title ",
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are the project teams that make up the governance structure for this engagement? ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 39,
                            AnswerSQL = "SELECT pt.Title, COUNT(wp.WorkPlanTaskType) AS MilestoneCount FROM WorkPlan wp LEFT JOIN ProjectTeams pt ON pt.ID = wp.ProjectTeamId WHERE wp.WorkPlanTaskType = 'Milestone' GROUP BY pt.Title ",
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many milestones does each team have? ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 40,
                            AnswerSQL = "SELECT      ReceiverTeam.Title AS ReceiverTeamName,     COUNT(1) AS InterdependencyCount FROM      Interdependencies AS I INNER JOIN      ProjectTeams AS ReceiverTeam ON I.ReceiverProjectTeamId = ReceiverTeam.ID GROUP BY      ReceiverTeam.Title ",
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many interdependencies does each team have ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 41,
                            AnswerSQL = "SELECT pt.Title, COUNT(1) AS RiskCount FROM RisksAndIssues RI left join ProjectTeams pt on pt.ID = ri.ProjectTeamId WHERE IssueRiskCategory = 'Risk' GROUP BY pt.Title ",
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many risks does each team have? ",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 42,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What PMO workplan templates are available?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 43,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the best practices to run weekly status meetings with the client?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 44,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What is the difference between Progress and Calculated Status?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 45,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do you add a new field to the workplan?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 46,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I set alerts/send email for various item owners?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 47,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I add a client user to the PMO app?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 48,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I link a Workplan Task to RAID?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 49,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY has supported in the past",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 50,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Help me understand PMO methodology for this ${ProjectType} project.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 51,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What cost savings levers are available?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 52,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What revenue growth levers are available?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 53,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are typical one-time costs that we should be considering?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 54,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the IT cost savings levers that I should be thinking about?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 55,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the one-time costs I should be expecting to incur for Supply Chain related initiatives?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 56,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do we evaluate our initiatives against one another to create an objective prioritization of what should be done first?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 57,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 58,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Help understand VC methodology.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 59,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What normative operating models are available?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 60,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How can I upload systems in bulk to the Op Model app?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 61,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the steps to setup the Op Model app?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 62,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What reports are available in the Op Model app?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 63,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY has supported in the past",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 64,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What TSAs would you suggest?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 65,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are examples for TSAs?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 66,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Why are TSAs important?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 67,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 68,
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What PMO workplan templates are available?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 69,
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the best practices to run weekly status meetings with the client?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 70,
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do you add a new field to the workplan?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 71,
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I link a Workplan Task to RAID?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 72,
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Help me understand PMO methodology for this ${ProjectType} project.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 73,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Generate a basic workplan template for my project.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 74,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key risks for a ${ProjectType} project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 75,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key milestones for a ${ProjectType} project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 76,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to run weekly status meetings?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 77,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are some of the similar deals that have happened in the past?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 78,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to build workplan, and track dependencies?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 79,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best cost saving initiatives?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 80,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best revenue growth initiatives?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 81,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best strategies for improving a company in the ${Sector} sector?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 82,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are recent examples of improvements being made in the ${Sector} sector?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 83,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best ways to track actuals?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 84,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What should be the frequency of tracking dollar values during the engagement?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 85,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are typical implications for cross border deals?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 86,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What is a normative operating model for the ${Sector} sector?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 87,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are key considerations when defining an operating model for a ${Sector} sector company?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 88,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are examples of Day 1 process dispositions?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 89,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the corporate functions typically involved in the ${Sector} sector?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 90,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the typical services of the Sales and Marketing function?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 91,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Draft a TSA for the Groceries Retail sector, Merchandising and Product Management function, and Endcap and Display Management service.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 92,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Provides templates of TSA",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 93,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What should be the typical duration for TSA",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 94,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Things I should keep in mind for longer duration TSAs",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 95,
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Generate a basic workplan template for my project.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 96,
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key risks for a ${ProjectType} project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 97,
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key milestones for a ${ProjectType} project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 98,
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to run weekly status meetings?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 99,
                            AppAffinity = "PROJECT_LEVEL",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to build workplan, and track dependencies?",
                            UpdatedBy = "System"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
