// <auto-generated />
using System;
using EY.CE.Copilot.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EY.CE.Copilot.Data.Migrations
{
    [DbContext(typeof(CopilotContext))]
    [Migration("20240408134803_UpdateSourceKeys")]
    partial class UpdateSourceKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.Suggestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnswerSQL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppAffinity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Suggestions", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8735),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8744),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 2,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8749),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8749),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 3,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8750),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8751),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 4,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8752),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8752),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 5,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8753),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8754),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 6,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8756),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8756),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 7,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8759),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8759),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 8,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8760),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8761),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 9,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8762),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8762),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 10,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8764),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8764),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 11,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8765),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8766),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 12,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8767),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8767),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 13,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8769),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8769),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 14,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8770),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8771),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 15,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8771),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8772),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 16,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8773),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8773),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 17,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8774),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8775),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 18,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8777),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8777),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 19,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8778),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8779),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 20,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8780),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8781),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 21,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8782),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8782),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 22,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8783),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8784),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 23,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8785),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8785),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 24,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8786),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8787),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 25,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8788),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many milestones does each team have?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8788),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 26,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8789),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many risks does each team have?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8790),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 27,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8791),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many dependencies does each team have?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8791),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 28,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8792),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which risks/issues have the most impact on the workplan?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8793),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 29,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8794),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out behind schedule milestones",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8794),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 30,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8795),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out behind schedule risks",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8796),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 31,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8797),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out behind schedule dependencies",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8797),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 32,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8798),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many milestones were assigned to me this week?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8799),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 33,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8800),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many risks were assigned to me this week?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8800),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 34,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8802),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many dependencies were assigned to me this week?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8803),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 35,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8804),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many of my milestones are due this week?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8804),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 36,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8805),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many risks are due this week?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8806),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 37,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8807),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many dependencies are due this week?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8807),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 38,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8808),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which project team has the most overdue milestones?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8809),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 39,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8810),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which project team has the most overdue risks?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8810),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 40,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8811),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which project team has the most overdue dependencies?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8812),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 41,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8813),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me open risks broken down by impact and probability",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8813),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 42,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8814),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are our targets for this engagement?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8815),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 43,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8816),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How much value are we planning to achieve from our initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8817),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 44,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8818),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How much value have we already achieved from our initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8818),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 45,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8819),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How are my initiatives doing?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8819),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 46,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8821),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Are there any risks or issues with initiatives that I’m responsible for?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8821),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 47,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8822),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which initiatives have fallen off track?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8823),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 48,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8824),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Are our initiative projections exceeding our targets?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8824),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 49,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8825),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How will these initiatives impact the PnL?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8826),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 50,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8827),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Provide a summary of Day 1 process dispositions.",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8828),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 51,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8829),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many systems are tagged to Current State processes?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8829),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 52,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8830),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many systems are tagged to Day 1 processes?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8831),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 53,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8832),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What team has the most Current State processes?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8832),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 54,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8833),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What team has the most Day 1 processes?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8834),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 55,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8835),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are some of the processes that have High impact Risk/Issue linked?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8835),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 56,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8837),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are the corporate functions typically involved in the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8837),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 57,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8838),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are the typical services of the Sales and Marketing function?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8839),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 58,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8840),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Draft a TSA for the Groceries Retail sector, Merchandising and Product Management function, and Endcap and Display Management service.",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8840),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 59,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8841),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the count of TSAs by function.",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8842),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 60,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8879),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the count of TSAs by sub function.",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8880),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 61,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8881),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the count of TSAs by region.",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8882),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 62,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8883),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many of the TSAs are behind schedule?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8883),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 63,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8884),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out TSAs that have high impact risks or issues associated with them.",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8885),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 64,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8886),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the breakdown of TSAs by duration",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8886),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 65,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8888),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What PMO workplan templates are available?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8888),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 66,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8890),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the best practices to run weekly status meetings with the client?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8890),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 67,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8891),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What is the difference between Progress and Calculated Status?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8892),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 68,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8893),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do you add a new field to the workplan?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8893),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 69,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8894),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do you hide a new field to the workplan?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8895),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 70,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8896),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do you rename a new field to the workplan?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8896),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 71,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8897),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to export report to PPT?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8898),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 72,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8899),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to export report to PDF?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8899),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 73,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8900),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I set alerts/send email for various item owners?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8901),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 74,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8902),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I add a client user to the PMO app?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8902),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 75,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8903),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I link a Workplan Task to RAID?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8904),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 76,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8905),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8905),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 77,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8906),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Help me understand PMO methodology for this ${ProjectType}",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8906),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 78,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8908),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What cost savings levers are available?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8908),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 79,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8909),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What revenue growth levers are available?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8910),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 80,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8911),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are typical one-time costs that we should be considering?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8911),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 81,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8912),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the IT cost savings levers that I should be thinking about?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8913),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 82,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8914),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the one-time costs I should be expecting to incur for Supply Chain related initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8914),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 83,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8915),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do we evaluate our initiatives against one another to create an objective prioritization of what should be done first?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8916),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 84,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8917),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8917),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 85,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8918),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Help understand VC methodology.",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8919),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 86,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8920),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What normative operating models are available?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8921),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 87,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8921),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How can I upload systems in bulk to the Op Model app?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8922),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 88,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8923),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the steps to setup the Op Model app?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8924),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 89,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8925),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Can I import an existing Operating Model in PowerPoint to use as my current state model?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8925),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 90,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8926),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What reports are available in the Op Model app?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8927),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 91,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8928),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8928),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 92,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8929),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What is a Process Group?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8930),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 93,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8930),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to view side by side view of current State/Day 1/Future state?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8931),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 94,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8932),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What TSAs would you suggest?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8933),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 95,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8934),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are examples for TSAs?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8934),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 96,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8935),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Why are TSAs important?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8936),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 97,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8937),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the most common types of TSAs?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8937),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 98,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8938),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8939),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 99,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8940),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to configure TSA stages?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8940),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 100,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8941),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to set alerts/send email to TSA owners",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8942),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 101,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8943),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Generate a basic workplan template for my project.",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8944),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 102,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8945),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key risks for a ${ProjectType} project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8945),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 103,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8946),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key milestones for a ${ProjectType} project?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8947),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 104,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8948),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to run weekly status meetings?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8948),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 105,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8949),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "When was the deal announced?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8950),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 106,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8951),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are some of the similar deals that have happened in the past?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8951),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 107,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8952),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to build workplan, and track dependencies?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8953),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 108,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8954),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best cost saving initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8955),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 109,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8956),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best revenue growth initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8956),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 110,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8957),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best strategies for improving a company in the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8958),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 111,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8959),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are recent examples of improvements being made in the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8959),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 112,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8960),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best ways to track actuals?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8961),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 113,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8962),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What should be the frequency of tracking dollar values during the engagement?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8962),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 114,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8963),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are typical implications for cross border deals?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8964),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 115,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8965),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What is a normative operating model for the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8965),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 116,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8966),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are key considerations when defining an operating model for a ${Sector} sector company?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8967),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 117,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8968),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are examples of Day 1 process dispositions?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8968),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 118,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8970),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the corporate functions typically involved in the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8970),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 119,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8971),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the typical services of the Sales and Marketing function?",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8972),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 120,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8973),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Draft a TSA for the Groceries Retail sector, Merchandising and Product Management function, and Endcap and Display Management service.",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8973),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 121,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8974),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Provides templates of TSA",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8975),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 122,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8976),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What should be the typical duration for TSA",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8976),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 123,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8977),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Things I should keep in mind for longer duration TSAs",
                            UpdatedAt = new DateTime(2024, 4, 8, 19, 18, 3, 317, DateTimeKind.Local).AddTicks(8978),
                            UpdatedBy = "System"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
