// <auto-generated />
using System;
using EY.CE.Copilot.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EY.CE.Copilot.Data.Migrations
{
    [DbContext(typeof(CopilotContext))]
    [Migration("20240403134317_SuggestionSeedData")]
    partial class SuggestionSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.Suggestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnswerSQL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppAffinity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Suggestions", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7940),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7959),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 2,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7965),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7965),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 3,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7967),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7968),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 4,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7969),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7970),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 5,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7971),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What is EY’s scope of work?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7972),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 6,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7975),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "Who is the program sponsor for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7975),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 7,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7978),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7979),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 8,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7980),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7981),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 9,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7983),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7983),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 10,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7986),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7987),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 11,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7988),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7989),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 12,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7990),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7991),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 13,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7992),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7993),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 14,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7995),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7995),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 15,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7997),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7997),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 16,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7999),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(7999),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 17,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8001),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8001),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 18,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8095),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8096),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 19,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8098),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8099),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 20,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8100),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8101),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 21,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8102),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8103),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 22,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8104),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8105),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 23,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8106),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8107),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 24,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8108),
                            CreatedBy = "System",
                            Source = "projectdoc",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8109),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 25,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8111),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How many milestones does each team have?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8112),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 26,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8113),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How many risks does each team have?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8114),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 27,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8115),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How many dependencies does each team have?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8116),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 28,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8117),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Which risks/issues have the most impact on the workplan?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8118),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 29,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8119),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "List out behind schedule milestones",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8120),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 30,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8121),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "List out behind schedule risks",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8122),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 31,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8123),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "List out behind schedule dependencies",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8124),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 32,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8125),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How many milestones were assigned to me this week?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8126),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 33,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8127),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How many risks were assigned to me this week?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8128),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 34,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8131),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How many dependencies were assigned to me this week?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8132),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 35,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8133),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How many of my milestones are due this week?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8134),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 36,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8135),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How many risks are due this week?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8136),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 37,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8137),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How many dependencies are due this week?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8138),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 38,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8139),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Which project team has the most overdue milestones?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8140),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 39,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8142),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Which project team has the most overdue risks?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8143),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 40,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8144),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Which project team has the most overdue dependencies?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8145),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 41,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8146),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Show me open risks broken down by impact and probability",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8147),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 42,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8148),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "What are our targets for this engagement?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8149),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 43,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8150),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How much value are we planning to achieve from our initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8151),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 44,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8152),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How much value have we already achieved from our initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8153),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 45,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8155),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How are my initiatives doing?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8155),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 46,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8157),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Are there any risks or issues with initiatives that I’m responsible for?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8157),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 47,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8159),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Which initiatives have fallen off track?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8160),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 48,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8161),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Are our initiative projections exceeding our targets?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8162),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 49,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8163),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How will these initiatives impact the PnL?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8164),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 50,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8165),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Provide a summary of Day 1 process dispositions.",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8166),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 51,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8167),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How many systems are tagged to Current State processes?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8168),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 52,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8169),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How many systems are tagged to Day 1 processes?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8170),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 53,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8171),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "What team has the most Current State processes?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8172),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 54,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8173),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "What team has the most Day 1 processes?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8174),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 55,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8175),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "What are some of the processes that have High impact Risk/Issue linked?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8176),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 56,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8178),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "What are the corporate functions typically involved in the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8179),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 57,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "What are the typical services of the Sales and Marketing function?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8181),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 58,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8182),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Draft a TSA for the Groceries Retail sector, Merchandising and Product Management function, and Endcap and Display Management service.",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8183),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 59,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8184),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Show me the count of TSAs by function.",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8185),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 60,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8186),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Show me the count of TSAs by sub function.",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8187),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 61,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8188),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Show me the count of TSAs by region.",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8189),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 62,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8190),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "How many of the TSAs are behind schedule?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8191),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 63,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8192),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "List out TSAs that have high impact risks or issues associated with them.",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8193),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 64,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8194),
                            CreatedBy = "System",
                            Source = "projectdata",
                            SuggestionText = "Show me the breakdown of TSAs by duration",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8195),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 65,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8197),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What PMO workplan templates are available?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8198),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 66,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8201),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What are the best practices to run weekly status meetings with the client?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8201),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 67,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8203),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What is the difference between Progress and Calculated Status?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8203),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 68,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8205),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How do you add a new field to the workplan?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8205),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 69,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8207),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How do you hide a new field to the workplan?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8208),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 70,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8209),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How do you rename a new field to the workplan?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8210),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 71,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8211),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How to export report to PPT?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8212),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 72,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8213),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How to export report to PDF?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8214),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 73,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8215),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How do I set alerts/send email for various item owners?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8216),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 74,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8217),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How do I add a client user to the PMO app?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8218),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 75,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8219),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How do I link a Workplan Task to RAID?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8220),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 76,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8221),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8222),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 77,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8223),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "Help me understand PMO methodology for this ${ProjectType}",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8224),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 78,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8226),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What cost savings levers are available?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8226),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 79,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8228),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What revenue growth levers are available?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8228),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 80,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8230),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What are typical one-time costs that we should be considering?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8230),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 81,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8232),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What are the IT cost savings levers that I should be thinking about?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8232),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 82,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8234),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What are the one-time costs I should be expecting to incur for Supply Chain related initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8234),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 83,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8236),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How do we evaluate our initiatives against one another to create an objective prioritization of what should be done first?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8237),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 84,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8238),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8239),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 85,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8240),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "Help understand VC methodology.",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8241),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 86,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8243),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What normative operating models are available?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8244),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 87,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8245),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How can I upload systems in bulk to the Op Model app?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8246),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 88,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8247),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What are the steps to setup the Op Model app?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8248),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 89,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8249),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "Can I import an existing Operating Model in PowerPoint to use as my current state model?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8250),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 90,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8306),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What reports are available in the Op Model app?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8307),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 91,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8309),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8310),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 92,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8311),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What is a Process Group?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8312),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 93,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8313),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How to view side by side view of current State/Day 1/Future state?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8314),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 94,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8316),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What TSAs would you suggest?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8316),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 95,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8318),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What are examples for TSAs?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8318),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 96,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8320),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "Why are TSAs important?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8320),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 97,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8322),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "What are the most common types of TSAs?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8322),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 98,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8324),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8325),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 99,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8326),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How to configure TSA stages?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8327),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 100,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8328),
                            CreatedBy = "System",
                            Source = "eyguidance",
                            SuggestionText = "How to set alerts/send email to TSA owners",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8329),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 101,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8331),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Generate a basic workplan template for my project.",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8332),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 102,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8333),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key risks for a ${ProjectType} project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8334),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 103,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8335),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key milestones for a ${ProjectType} project?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8336),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 104,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8337),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to run weekly status meetings?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8338),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 105,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8339),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "When was the deal announced?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8340),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 106,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8341),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are some of the similar deals that have happened in the past?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8342),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 107,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8343),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to build workplan, and track dependencies?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8344),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 108,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8346),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best cost saving initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8347),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 109,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8348),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best revenue growth initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8349),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 110,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8350),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best strategies for improving a company in the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8351),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 111,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8352),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are recent examples of improvements being made in the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8353),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 112,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8354),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best ways to track actuals?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8355),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 113,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8356),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What should be the frequency of tracking dollar values during the engagement?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8357),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 114,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8358),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are typical implications for cross border deals?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8359),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 115,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8361),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What is a normative operating model for the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8362),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 116,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8363),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are key considerations when defining an operating model for a ${Sector} sector company?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8364),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 117,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8365),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are examples of Day 1 process dispositions?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8366),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 118,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8368),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the corporate functions typically involved in the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8368),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 119,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8370),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the typical services of the Sales and Marketing function?",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8370),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 120,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8372),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Draft a TSA for the Groceries Retail sector, Merchandising and Product Management function, and Endcap and Display Management service.",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8372),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 121,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8374),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Provides templates of TSA",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8374),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 122,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8376),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What should be the typical duration for TSA",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8377),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 123,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8378),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Things I should keep in mind for longer duration TSAs",
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 13, 16, 392, DateTimeKind.Local).AddTicks(8379),
                            UpdatedBy = "System"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
