// <auto-generated />
using System;
using EY.CE.Copilot.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EY.CE.Copilot.Data.Migrations
{
    [DbContext(typeof(CopilotContext))]
    [Migration("20240410134937_CopilotConfigurationSeeding")]
    partial class CopilotConfigurationSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.CopilotConfiguration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CopilotConfigurations", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsEnabled = false,
                            Key = "PROJECT_CONTEXT",
                            Title = "Project Context",
                            Value = ""
                        });
                });

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.Suggestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnswerSQL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppAffinity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Suggestions", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8453),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8469),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 2,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8473),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8473),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 3,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8474),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8475),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 4,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8476),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8476),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 5,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8477),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8478),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 6,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8479),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8480),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 7,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8481),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8482),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 8,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8483),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8483),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 9,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8484),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8485),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 10,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8486),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8486),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 11,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8487),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8488),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 12,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8488),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8489),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 13,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8490),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8491),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 14,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8491),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8492),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 15,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8493),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8493),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 16,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8494),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8494),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 17,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8495),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8496),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 18,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8497),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8498),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 19,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8499),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8499),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 20,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8500),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8501),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 21,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8502),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8502),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 22,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8503),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8503),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 23,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8504),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8505),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 24,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8505),
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8506),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 25,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8507),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many milestones does each team have?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8507),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 26,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8508),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many risks does each team have?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8509),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 27,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8510),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many dependencies does each team have?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8510),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 28,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8511),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which risks/issues have the most impact on the workplan?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8511),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 29,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8512),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out behind schedule milestones",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8513),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 30,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8514),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out behind schedule risks",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8514),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 31,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8515),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out behind schedule dependencies",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8515),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 32,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8516),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many milestones were assigned to me this week?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8517),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 33,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8518),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many risks were assigned to me this week?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8518),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 34,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8520),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many dependencies were assigned to me this week?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8520),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 35,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8521),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many of my milestones are due this week?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8521),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 36,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8522),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many risks are due this week?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8523),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 37,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8569),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many dependencies are due this week?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8569),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 38,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8570),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which project team has the most overdue milestones?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8571),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 39,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8571),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which project team has the most overdue risks?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8572),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 40,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8573),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which project team has the most overdue dependencies?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8573),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 41,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8574),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me open risks broken down by impact and probability",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8575),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 42,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8576),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are our targets for this engagement?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8576),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 43,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8577),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How much value are we planning to achieve from our initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8578),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 44,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8578),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How much value have we already achieved from our initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8579),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 45,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8580),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How are my initiatives doing?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8580),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 46,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8581),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Are there any risks or issues with initiatives that I’m responsible for?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8581),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 47,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8582),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which initiatives have fallen off track?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8583),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 48,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8584),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Are our initiative projections exceeding our targets?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8584),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 49,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8585),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How will these initiatives impact the PnL?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8585),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 50,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8587),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Provide a summary of Day 1 process dispositions.",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8587),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 51,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8588),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many systems are tagged to Current State processes?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8588),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 52,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8589),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many systems are tagged to Day 1 processes?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8590),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 53,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8590),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What team has the most Current State processes?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8591),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 54,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8592),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What team has the most Day 1 processes?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8592),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 55,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8593),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are some of the processes that have High impact Risk/Issue linked?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8594),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 56,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8595),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are the corporate functions typically involved in the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8595),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 57,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8596),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are the typical services of the Sales and Marketing function?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8596),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 58,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8597),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Draft a TSA for the Groceries Retail sector, Merchandising and Product Management function, and Endcap and Display Management service.",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8598),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 59,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8599),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the count of TSAs by function.",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8599),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 60,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8600),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the count of TSAs by sub function.",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8600),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 61,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8601),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the count of TSAs by region.",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8602),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 62,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8602),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many of the TSAs are behind schedule?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8603),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 63,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8604),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out TSAs that have high impact risks or issues associated with them.",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8604),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 64,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8605),
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the breakdown of TSAs by duration",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8606),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 65,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8607),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What PMO workplan templates are available?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8607),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 66,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8609),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the best practices to run weekly status meetings with the client?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8610),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 67,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8610),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What is the difference between Progress and Calculated Status?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8611),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 68,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8612),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do you add a new field to the workplan?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8612),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 69,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8613),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do you hide a new field to the workplan?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8613),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 70,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8614),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do you rename a new field to the workplan?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8615),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 71,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8615),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to export report to PPT?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8616),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 72,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8617),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to export report to PDF?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8617),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 73,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8618),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I set alerts/send email for various item owners?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8618),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 74,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8619),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I add a client user to the PMO app?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8620),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 75,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8621),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I link a Workplan Task to RAID?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8621),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 76,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8622),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8622),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 77,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8623),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Help me understand PMO methodology for this ${ProjectType}",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8623),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 78,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8625),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What cost savings levers are available?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8625),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 79,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8626),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What revenue growth levers are available?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8626),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 80,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8627),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are typical one-time costs that we should be considering?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8628),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 81,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8628),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the IT cost savings levers that I should be thinking about?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8629),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 82,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8630),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the one-time costs I should be expecting to incur for Supply Chain related initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8630),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 83,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8631),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do we evaluate our initiatives against one another to create an objective prioritization of what should be done first?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8631),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 84,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8632),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8633),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 85,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8633),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Help understand VC methodology.",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8634),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 86,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8635),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What normative operating models are available?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8635),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 87,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8636),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How can I upload systems in bulk to the Op Model app?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8637),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 88,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8638),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the steps to setup the Op Model app?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8638),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 89,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8639),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Can I import an existing Operating Model in PowerPoint to use as my current state model?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8639),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 90,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8640),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What reports are available in the Op Model app?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8640),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 91,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8641),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8642),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 92,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8643),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What is a Process Group?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8643),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 93,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8644),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to view side by side view of current State/Day 1/Future state?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8644),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 94,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8645),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What TSAs would you suggest?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8646),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 95,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8647),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are examples for TSAs?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8647),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 96,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8648),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Why are TSAs important?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8648),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 97,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8649),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the most common types of TSAs?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8650),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 98,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8650),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8651),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 99,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8652),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to configure TSA stages?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8652),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 100,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8653),
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to set alerts/send email to TSA owners",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8653),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 101,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8654),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Generate a basic workplan template for my project.",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8655),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 102,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8656),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key risks for a ${ProjectType} project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8656),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 103,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8657),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key milestones for a ${ProjectType} project?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8657),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 104,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8658),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to run weekly status meetings?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8659),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 105,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8659),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "When was the deal announced?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8660),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 106,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8661),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are some of the similar deals that have happened in the past?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8661),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 107,
                            AnswerSQL = "",
                            AppAffinity = "CE4-PMO",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8662),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to build workplan, and track dependencies?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8663),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 108,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8664),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best cost saving initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8664),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 109,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8665),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best revenue growth initiatives?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8665),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 110,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8666),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best strategies for improving a company in the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8667),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 111,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8668),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are recent examples of improvements being made in the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8668),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 112,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8669),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best ways to track actuals?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8669),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 113,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8670),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What should be the frequency of tracking dollar values during the engagement?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8671),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 114,
                            AnswerSQL = "",
                            AppAffinity = "CE4-VC",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8671),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are typical implications for cross border deals?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8672),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 115,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8749),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What is a normative operating model for the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8750),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 116,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8751),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are key considerations when defining an operating model for a ${Sector} sector company?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8751),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 117,
                            AnswerSQL = "",
                            AppAffinity = "CE4-OM",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8752),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are examples of Day 1 process dispositions?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8753),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 118,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8754),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the corporate functions typically involved in the ${Sector} sector?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8755),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 119,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8755),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the typical services of the Sales and Marketing function?",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8756),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 120,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8757),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Draft a TSA for the Groceries Retail sector, Merchandising and Product Management function, and Endcap and Display Management service.",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8757),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 121,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8758),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Provides templates of TSA",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8758),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 122,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8759),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What should be the typical duration for TSA",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8760),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 123,
                            AnswerSQL = "",
                            AppAffinity = "CE4-TSA",
                            CreatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8761),
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Things I should keep in mind for longer duration TSAs",
                            UpdatedAt = new DateTime(2024, 4, 10, 19, 19, 36, 877, DateTimeKind.Local).AddTicks(8761),
                            UpdatedBy = "System"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
