// <auto-generated />
using System;
using EY.CE.Copilot.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EY.CE.Copilot.Data.Migrations
{
    [DbContext(typeof(CopilotContext))]
    [Migration("20240425142622_ProjectLevelDataInSuggestion")]
    partial class ProjectLevelDataInSuggestion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.ChatHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MessageId")
                        .HasColumnType("int");

                    b.Property<long?>("SuggestionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TimeToResolve")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ChatHistorys");
                });

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.CopilotConfiguration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CopilotConfigurations", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsEnabled = false,
                            Key = "PROJECT_CONTEXT",
                            Title = "Project Context",
                            Value = ""
                        });
                });

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.CopilotFeedback", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("CopilotFeedbacks");
                });

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.MessageFeedback", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("bit");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("MessageFeedbacks");
                });

            modelBuilder.Entity("EY.CE.Copilot.Data.Models.Suggestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnswerSQL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppAffinity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Suggestions", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 2,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 3,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 4,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 5,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 6,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 7,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 8,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 9,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 10,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 11,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 12,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 13,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 14,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 15,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 16,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 17,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 18,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 19,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 20,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 21,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 22,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 23,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 24,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 25,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is the governance structure for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 26,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "List out various recurring meetings along with cadence",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 27,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What are key dates for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 28,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What do we know about the target and buyer for this project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 29,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "What is EY’s scope of work ?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 30,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "project-docs",
                            SuggestionText = "Who is the program sponsor for this project ?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 31,
                            AnswerSQL = "SELECT pt.Title, COUNT(wp.WorkPlanTaskType) AS MilestoneCount FROM WorkPlan wp LEFT JOIN ProjectTeams pt ON pt.ID = wp.ProjectTeamId WHERE wp.WorkPlanTaskType = 'Milestone' GROUP BY pt.Title;",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many milestones does each team have?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 32,
                            AnswerSQL = "SELECT pt.Title, COUNT(*) AS RiskCount FROM RisksAndIssues RI left join ProjectTeams pt on pt.ID = ri.ProjectTeamId WHERE IssueRiskCategory = 'Risk' GROUP BY pt.Title;",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many risks does each team have?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 33,
                            AnswerSQL = "SELECT      ReceiverTeam.Title AS ReceiverTeamName,     COUNT(*) AS InterdependencyCount FROM      Interdependencies AS I INNER JOIN      ProjectTeams AS ReceiverTeam ON I.ReceiverProjectTeamId = ReceiverTeam.ID GROUP BY      ReceiverTeam.Title",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many dependencies does each team have?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 34,
                            AnswerSQL = "select wp.Title, ri.Title from WorkPlansToRisksAndIssuesForAssociatedRisksAndIssues WTRI left join workplan wp on wp.ID = WTRI.WorkPlanId left join RisksAndIssues ri on ri.ID = WTRI.RisksAndIssueId",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which risks/issues have the most impact on the workplan?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 35,
                            AnswerSQL = "SELECT wp.Title from WorkPlan wp LEFT JOIN Statuses s on wp.WorkPlanTaskStatusId = s.ID where s.[Key] = 'BEHIND_SCHEDULE'",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out behind schedule milestones",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 36,
                            AnswerSQL = "SELECT RI.Title from RisksAndIssues RI LEFT JOIN Statuses s on RI.ItemStatusId = s.ID where s.[Key] = 'BEHIND_SCHEDULE'",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out behind schedule risks",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 37,
                            AnswerSQL = "SELECT I.Title from Interdependencies I LEFT JOIN Statuses s on I.InterdependencyStatusId = s.ID where s.[Key] = 'BEHIND_SCHEDULE'",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out behind schedule dependencies",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 38,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many milestones were assigned to me this week?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 39,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many risks were assigned to me this week?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 40,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many dependencies were assigned to me this week?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 41,
                            AnswerSQL = "SELECT COUNT(*) AS MilestonesDueThisWeek FROM WorkPlan wp LEFT JOIN statuses s ON wp.WorkPlanTaskStatusId = s.ID WHERE wp.WorkPlanTaskType = 'Milestone'   AND YEAR(wp.TaskDueDate) = YEAR(GETDATE())   AND DATEPART(WEEK, wp.TaskDueDate) = DATEPART(WEEK, GETDATE())   AND (s.[Key] IS NULL OR s.[Key]  NOT IN ('COMPLETED', 'CLOSED'));",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many of my milestones are due this week?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 42,
                            AnswerSQL = "SELECT COUNT(*) AS RisksAndIssuesDueThisWeek FROM RisksAndIssues RI LEFT JOIN statuses S ON RI.ItemStatusId = S.ID WHERE RI.IssueRiskCategory = 'Risk'   AND YEAR(RI.ItemDueDate) = YEAR(GETDATE())   AND DATEPART(WEEK, RI.ItemDueDate) = DATEPART(WEEK, GETDATE())   AND (S.[Key] IS NULL OR S.[Key] NOT IN ('COMPLETED', 'CLOSED'));",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many risks are due this week?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 43,
                            AnswerSQL = "SELECT      COUNT(*) AS InterdependenciesDueThisWeek FROM      Interdependencies I LEFT JOIN      statuses S ON I.InterdependencyStatusId = S.ID WHERE      YEAR(I.ItemDueDate) = YEAR(GETDATE())     AND DATEPART(WEEK, I.ItemDueDate) = DATEPART(WEEK, GETDATE())     AND (S.[Key] IS NULL OR S.[Key] NOT IN ('COMPLETED', 'CLOSED'));",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many dependencies are due this week?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 44,
                            AnswerSQL = "SELECT     pt.Title AS ProjectTeamTitle,     COUNT(*) AS OverdueMilestoneCount FROM      WorkPlan wp INNER JOIN      ProjectTeams pt ON wp.ProjectTeamId = pt.ID LEFT JOIN      statuses s ON wp.WorkPlanTaskStatusId = s.ID WHERE      wp.WorkPlanTaskType = 'Milestone'     AND wp.TaskDueDate < GETDATE()     AND (s.[Key] IS NULL OR s.[Key] NOT IN ('COMPLETED', 'CLOSED')) GROUP BY      pt.Title ORDER BY      OverdueMilestoneCount DESC",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which project team has the most overdue milestones?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 45,
                            AnswerSQL = "SELECT      pt.Title AS ProjectTeamTitle,     COUNT(*) AS OverdueRiskCount FROM      RisksAndIssues RI INNER JOIN      ProjectTeams pt ON RI.ProjectTeamId = pt.ID LEFT JOIN      statuses S ON RI.ItemStatusId = S.ID WHERE      RI.IssueRiskCategory = 'Risk'     AND RI.ItemDueDate < GETDATE()     AND (S.[Key] IS NULL OR S.[Key] NOT IN ('COMPLETED', 'CLOSED')) GROUP BY      pt.Title ORDER BY ",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which project team has the most overdue risks?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 46,
                            AnswerSQL = "SELECT      ReceiverTeam.Title AS ReceiverTeamTitle,     COUNT(*) AS OverdueDependencyCount FROM      Interdependencies I INNER JOIN      ProjectTeams ReceiverTeam ON I.ReceiverProjectTeamId = ReceiverTeam.ID LEFT JOIN      statuses S ON I.InterdependencyStatusId = S.ID WHERE      I.ItemDueDate < GETDATE()     AND (S.[Key] IS NULL OR S.[Key] NOT IN ('COMPLETED', 'CLOSED')) GROUP BY      ReceiverTeam.Title ORDER BY      OverdueDependencyCount DESC;",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which project team has the most overdue dependencies?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 47,
                            AnswerSQL = "SELECT      RiskImpact,     RiskProbability,     COUNT(*) AS RiskCount FROM      RisksAndIssues WHERE      IssueRiskCategory = 'Risk'     AND ItemStatusId NOT IN (SELECT ID FROM statuses WHERE [Key] IN ('COMPLETED', 'CLOSED')) AND (RiskImpact IS NOT NULL  OR RiskProbability IS NOT NULL ) GROUP BY      RiskImpact,     RiskProbability ORDER BY      RiskImpact, RiskProbability;",
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me open risks broken down by impact and probability",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 48,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are our targets for this engagement?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 49,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How much value are we planning to achieve from our initiatives?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 50,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How much value have we already achieved from our initiatives?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 51,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How are my initiatives doing?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 52,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Are there any risks or issues with initiatives that I’m responsible for?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 53,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Which initiatives have fallen off track?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 54,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Are our initiative projections exceeding our targets?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 55,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How will these initiatives impact the PnL?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 56,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Provide a summary of Day 1 process dispositions.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 57,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many systems are tagged to Current State processes?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 58,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many systems are tagged to Day 1 processes?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 59,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What team has the most Current State processes?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 60,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What team has the most Day 1 processes?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 61,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are some of the processes that have High impact Risk/Issue linked?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 62,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are the corporate functions typically involved in the ${Sector} sector?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 63,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are the typical services of the Sales and Marketing function?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 64,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Draft a TSA for the Groceries Retail sector, Merchandising and Product Management function, and Endcap and Display Management service.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 65,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the count of TSAs by function.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 66,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the count of TSAs by sub function.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 67,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the count of TSAs by region.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 68,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many of the TSAs are behind schedule?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 69,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "List out TSAs that have high impact risks or issues associated with them.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 70,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Show me the breakdown of TSAs by duration",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 71,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "Provide a summary of Day 1 process dispositions.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 72,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many systems are tagged to Current State processes?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 73,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "How many systems are tagged to Day 1 processes?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 74,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What team has the most Current State processes?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 75,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What team has the most Day 1 processes?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 76,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "project-data",
                            SuggestionText = "What are some of the processes that have High impact Risk/Issue linked?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 77,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What PMO workplan templates are available?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 78,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the best practices to run weekly status meetings with the client?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 79,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What is the difference between Progress and Calculated Status?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 80,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do you add a new field to the workplan?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 81,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do you hide a new field to the workplan?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 82,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do you rename a new field to the workplan?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 83,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to export report to PPT?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 84,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to export report to PDF?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 85,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I set alerts/send email for various item owners?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 86,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I add a client user to the PMO app?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 87,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I link a Workplan Task to RAID?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 88,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 89,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Help me understand PMO methodology for this ${ProjectType}",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 90,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What cost savings levers are available?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 91,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What revenue growth levers are available?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 92,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are typical one-time costs that we should be considering?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 93,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the IT cost savings levers that I should be thinking about?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 94,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the one-time costs I should be expecting to incur for Supply Chain related initiatives?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 95,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do we evaluate our initiatives against one another to create an objective prioritization of what should be done first?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 96,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 97,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Help understand VC methodology.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 98,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What normative operating models are available?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 99,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How can I upload systems in bulk to the Op Model app?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 100,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the steps to setup the Op Model app?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 101,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Can I import an existing Operating Model in PowerPoint to use as my current state model?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 102,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What reports are available in the Op Model app?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 103,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 104,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What is a Process Group?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 105,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to view side by side view of current State/Day 1/Future state?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 106,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What TSAs would you suggest?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 107,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are examples for TSAs?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 108,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Why are TSAs important?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 109,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the most common types of TSAs?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 110,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Provide case studies/credentials for similar deals that EY have supported in the past",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 111,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to configure TSA stages?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 112,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to set alerts/send email to TSA owners",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 113,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What PMO workplan templates are available?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 114,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "What are the best practices to run weekly status meetings with the client?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 115,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do you add a new field to the workplan?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 116,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How to export report to PPT?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 117,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I set alerts/send email for various item owners?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 118,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "How do I link a Workplan Task to RAID?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 119,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "ey-guidance",
                            SuggestionText = "Help me understand PMO methodology for this ${ProjectType}",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 120,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Generate a basic workplan template for my project.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 121,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key risks for a ${ProjectType} project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 122,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key milestones for a ${ProjectType} project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 123,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to run weekly status meetings?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 124,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "When was the deal announced?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 125,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are some of the similar deals that have happened in the past?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 126,
                            AppAffinity = "CE4-PMO",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to build workplan, and track dependencies?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 127,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best cost saving initiatives?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 128,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best revenue growth initiatives?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 129,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best strategies for improving a company in the ${Sector} sector?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 130,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are recent examples of improvements being made in the ${Sector} sector?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 131,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best ways to track actuals?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 132,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What should be the frequency of tracking dollar values during the engagement?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 133,
                            AppAffinity = "CE4-VC",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are typical implications for cross border deals?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 134,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What is a normative operating model for the ${Sector} sector?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 135,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are key considerations when defining an operating model for a ${Sector} sector company?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 136,
                            AppAffinity = "CE4-OM",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are examples of Day 1 process dispositions?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 137,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the corporate functions typically involved in the ${Sector} sector?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 138,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the typical services of the Sales and Marketing function?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 139,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Draft a TSA for the Groceries Retail sector, Merchandising and Product Management function, and Endcap and Display Management service.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 140,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Provides templates of TSA",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 141,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What should be the typical duration for TSA",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 142,
                            AppAffinity = "CE4-TSA",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Things I should keep in mind for longer duration TSAs",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 143,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "Generate a basic workplan template for my project.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 144,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key risks for a ${ProjectType} project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 145,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the key milestones for a ${ProjectType} project?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 146,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to run weekly status meetings?",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            ID = 147,
                            AppAffinity = "CE4-PL",
                            CreatedBy = "System",
                            Source = "internet",
                            SuggestionText = "What are the best practices to build workplan, and track dependencies?",
                            UpdatedBy = "System"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
