apiVersion: batch/v1
kind: CronJob
metadata:
  name: chatbot-ai-search-project-specific 
  labels:
    aadpodidbinding: ce5-managed-identity
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            aadpodidbinding: ce5-managed-identity
        spec:
          automountServiceAccountToken: false
          containers:
          - name: chatbot-ai-search-project-specific
            image: #{ACRName}#.azurecr.io/chatbot-ai-search-project-specific:#{CronjobBuildId}#
            envFrom:
            - configMapRef:
               name: chatbot-ai-search-project-specific
            imagePullPolicy: Always    
          restartPolicy: OnFailure
      backoffLimit: 2
