// env.config.prod.ts
const config = {
  PUBLIC_URL: "[PUBLIC_URL]",
  REACT_APP_API_URL: "[REACT_APP_API_URL]",
  REACT_APP_URL: "[REACT_APP_URL]",
  REACT_APP_ENGAGE_MGMT_GUIDANCE_URL: "[REACT_APP_ENGAGE_MGMT_GUIDANCE_URL]",
  AZURE_AD_AUTHORITY: "[AZURE_AD_AUTHORITY]",
  AZURE_AD_CLIENT_ID: "[AZURE_AD_CLIENT_ID]",
  AZURE_AD_APP_SCOPE: "[AZURE_AD_APP_SCOPE]",
  AZURE_AD_API_SCOPE: "[AZURE_AD_API_SCOPE]",
  TOKEN_RENEWAL_OFFSET_SECONDS: "[TOKEN_RENEWAL_OFFSET_SECONDS]",
  PROJECT_ID: "[PROJECT_ID]",
  SSP_API_URL: "[SSP_API_URL]",
  EY_AI_PRINCIPLES: "[EY_AI_PRINCIPLES]",
  MICROSOFT_ACCEPTABLE_USE_POLICY_URL: "[MICROSOFT_ACCEPTABLE_USE_POLICY_URL]",
  MICROSOFT_CODE_OF_CONDUCT_OPENAI_SERVICES_URL:
    "[MICROSOFT_CODE_OF_CONDUCT_OPENAI_SERVICES_URL]",
  APPLICATION_INSIGHTS_KEY : "[APPLICATION_INSIGHTS_KEY]",
  AG_GRID_LICENSE_KEY : "[AG_GRID_LICENSE_KEY]"
};

export default config;
