# Base image
FROM python:3.12

# Working Directory
WORKDIR /app

COPY ./requirements/requeriments_pc.txt /app/requirements.txt

# Install requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Remove git
RUN apt-get remove --purge -y git && \
    apt-get autoremove -y

# Copy ingest and index scripts
COPY ./Indexes/index_core_functions.py /app/index_core_functions.py
COPY ./Indexes/prj_glossary.json /app/prj_glossary.json
COPY ./Indexes/index_project_specific_cronjob.py /app/index_project_specific_cronjob.py
COPY logger.py /app/logger.py


RUN useradd -m nonroot
USER nonroot

# Run scripts
CMD python /app/index_project_specific_cronjob.py
