# Base image
FROM python:3.12

# Set environment variables for the ODBC driver version
ENV ACCEPT_EULA=Y
ENV ODBC_DRIVER_VERSION=18

# Working Directory
WORKDIR /app

COPY ./requirements/requeriments_gc.txt /app/requirements.txt

# Install requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Remove git
RUN apt-get remove --purge -y git && \
    apt-get autoremove -y
 
# Install necessary tools for the ODBC driver installation
RUN apt-get update && apt-get install -y --no-install-recommends \
    gnupg \
    unixodbc \
    unixodbc-dev \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
 
# Add Microsoft repository for the ODBC driver
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list
 
# Install the Microsoft ODBC Driver for SQL Server
RUN apt-get update && apt-get install -y --no-install-recommends \
    msodbcsql${ODBC_DRIVER_VERSION} \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
 
# Clean up the apt cache to reduce image size
RUN apt-get clean && rm -rf /var/lib/apt/lists/*


# Copy ingest and index scripts
COPY ./Ingest/ /app
COPY ./Indexes/index_core_functions.py /app/index_core_functions.py
COPY ./Indexes/index_general_context_cronjob.py /app/index_general_context_cronjob.py
COPY logger.py /app/logger.py

RUN useradd -m nonroot
USER nonroot

# Run scripts
CMD python /app/comparison_cronjob.py && python /app/index_general_context_cronjob.py
